import os
import shutil
from pathlib import Path

from snakemake.api import SnakemakeApi
from snakemake.settings.types import ExecutionSettings, OutputSettings, \
    ResourceSettings

from merlin.util import snakewriter
from merlin.analysis import testtask


def _run_snakefile_locally(snakefilePath):
    # Mirrors merlin.merlin.run_with_snakemake's local-execution call --
    # see that function's docstring for why the pre-8.0
    # snakemake.snakemake(...) flat call no longer works.
    with SnakemakeApi(OutputSettings()) as snakemakeApi:
        workflowApi = snakemakeApi.workflow(
            resource_settings=ResourceSettings(cores=1),
            snakefile=Path(snakefilePath),
            workdir=Path(os.getcwd()))
        dagApi = workflowApi.dag(dag_settings=None)
        dagApi.execute_workflow(
            executor='local',
            execution_settings=ExecutionSettings(lock=False,
                                                  latency_wait=10,
                                                  keep_going=True))


def test_run_single_task(simple_merfish_task):
    simple_merfish_task.save()
    assert not simple_merfish_task.is_complete()
    snakeRule = snakewriter.SnakemakeRule(simple_merfish_task)
    with open('temp.Snakefile', 'w') as outFile:
        outFile.write('rule all: \n\tinput: '
                      + snakeRule.full_output() + '\n\n')
        outFile.write(snakeRule.as_string())

    _run_snakefile_locally('temp.Snakefile')
    os.remove('temp.Snakefile')
    shutil.rmtree('.snakemake')

    assert simple_merfish_task.is_complete()


def test_snakemake_generator_one_task(simple_merfish_data):
    taskDict = {'analysis_tasks': [
        {'task': 'SimpleAnalysisTask',
         'module': 'merlin.analysis.testtask',
         'parameters': {}}
    ]}

    generator = snakewriter.SnakefileGenerator(taskDict, simple_merfish_data)
    workflow = generator.generate_workflow()
    outputTask = simple_merfish_data.load_analysis_task('SimpleAnalysisTask')
    assert not outputTask.is_complete()
    _run_snakefile_locally(workflow)
    assert outputTask.is_complete()

    shutil.rmtree('.snakemake')


def test_snakemake_generator_task_chain(simple_merfish_data):
    taskDict = {'analysis_tasks': [
        {'task': 'SimpleAnalysisTask',
         'module': 'merlin.analysis.testtask',
         'analysis_name': 'Task1',
         'parameters': {}},
        {'task': 'SimpleParallelAnalysisTask',
         'module': 'merlin.analysis.testtask',
         'analysis_name': 'Task2',
         'parameters': {'dependencies': ['Task1']}},
        {'task': 'SimpleParallelAnalysisTask',
         'module': 'merlin.analysis.testtask',
         'analysis_name': 'Task3',
         'parameters': {'dependencies': ['Task2']}}
    ]}

    generator = snakewriter.SnakefileGenerator(taskDict, simple_merfish_data)
    workflow = generator.generate_workflow()
    outputTask1 = simple_merfish_data.load_analysis_task('Task1')
    outputTask2 = simple_merfish_data.load_analysis_task('Task2')
    outputTask3 = simple_merfish_data.load_analysis_task('Task3')
    assert not outputTask1.is_complete()
    assert not outputTask2.is_complete()
    assert not outputTask3.is_complete()
    _run_snakefile_locally(workflow)
    assert outputTask1.is_complete()
    assert outputTask2.is_complete()
    assert outputTask3.is_complete()

    shutil.rmtree('.snakemake')


def test_translate_cluster_resources():
    # Mirrors a real cluster_resource_allocation_*.json '__default__' block
    # merged with a per-task override (e.g. CellPoseSegmentSAM), as
    # generated by MERci's create_cluster_resource_allocation.
    merged = {
        'account': 'zhuang_lab', 'time': '0:10:00', 'n': 1,
        'partition': 'gpu_requeue,gpu', 'mem': 32000, 'constraint': '',
        'exclude': 'holygpu7c0309,holygpu7c0711', 'requeue': False,
        'gres': 'gpu:1'}
    resources = snakewriter._translate_cluster_resources(merged)
    assert resources == {
        'mem_mb': 32000,
        'slurm_partition': 'gpu_requeue,gpu',
        'slurm_account': 'zhuang_lab',
        'runtime': 10,
        'gres': 'gpu:1',
        'slurm_extra': '--exclude=holygpu7c0309,holygpu7c0711'}
    # empty 'constraint' is dropped rather than passed through as '-C ""'


def test_translate_cluster_resources_omits_zero_gres():
    # Real bug, caught on a real SLURM submission: 'gpu:0' is the
    # __default__ for every non-GPU task (a no-op under the old sbatch
    # template), but snakemake-executor-plugin-slurm treats any 'gpu'
    # substring in `gres` as a GPU job and adds --ntasks-per-gpu=1
    # unconditionally, which sbatch rejects when paired with zero GPUs.
    default = {'account': 'zhuang_lab', 'time': '3:00:00', 'mem': 8000,
               'partition': 'zhuang,sapphire,serial_requeue',
               'constraint': '', 'exclude': '', 'requeue': False,
               'gres': 'gpu:0'}
    resources = snakewriter._translate_cluster_resources(default)
    assert 'gres' not in resources


def test_translate_cluster_resources_time_with_days():
    assert snakewriter._parse_slurm_time_to_minutes('2-03:15:30') \
        == 2*24*60 + 3*60 + 15 + 1
    assert snakewriter._parse_slurm_time_to_minutes('3:00:00') == 180


def test_snakemake_rule_resources_block(simple_merfish_task):
    clusterConfig = {
        '__default__': {'account': 'zhuang_lab', 'time': '3:00:00',
                         'mem': 8000, 'partition': 'zhuang'},
        simple_merfish_task.get_analysis_name(): {'mem': 5000},
    }
    snakeRule = snakewriter.SnakemakeRule(
        simple_merfish_task, clusterConfig=clusterConfig)
    ruleString = snakeRule.as_string()
    # the per-task override (mem=5000) wins over __default__'s mem=8000,
    # while __default__'s account/time/partition still apply
    assert "resources: mem_mb=5000, slurm_partition='zhuang', " \
        "slurm_account='zhuang_lab', runtime=180" in ruleString


def test_snakemake_rule_resources_uses_computed_estimate_with_margin(
        simple_merfish_data):
    task = testtask.SimpleAnalysisTaskWithResourceEstimate(
        simple_merfish_data,
        parameters={'estimated_memory': 1000, 'estimated_time': 10})
    snakeRule = snakewriter.SnakemakeRule(task)
    ruleString = snakeRule.as_string()
    # 1000 * 1.2 = 1200, 10 * 1.2 = 12 (RESOURCE_ESTIMATE_MARGIN)
    assert 'resources: mem_mb=1200, runtime=12' in ruleString
    simple_merfish_data.delete_analysis(task)


def test_snakemake_rule_resources_explicit_override_wins_over_estimate(
        simple_merfish_data):
    task = testtask.SimpleAnalysisTaskWithResourceEstimate(
        simple_merfish_data,
        parameters={'estimated_memory': 1000, 'estimated_time': 10})
    clusterConfig = {task.get_analysis_name(): {'mem': 5000, 'time': '0:20:00'}}
    snakeRule = snakewriter.SnakemakeRule(task, clusterConfig=clusterConfig)
    ruleString = snakeRule.as_string()
    # the rule's own explicit mem/time entry wins over the computed
    # estimate entirely -- not even margined
    assert 'mem_mb=5000' in ruleString
    assert 'runtime=20' in ruleString
    assert 'mem_mb=1200' not in ruleString
    simple_merfish_data.delete_analysis(task)


def test_snakemake_rule_resources_default_only_does_not_override_estimate(
        simple_merfish_data):
    # __default__ is a fallback for every rule, not a real per-rule
    # override -- a computed estimate should still win over it.
    task = testtask.SimpleAnalysisTaskWithResourceEstimate(
        simple_merfish_data,
        parameters={'estimated_memory': 1000, 'estimated_time': 10})
    clusterConfig = {'__default__': {'mem': 8000, 'time': '3:00:00'}}
    snakeRule = snakewriter.SnakemakeRule(task, clusterConfig=clusterConfig)
    ruleString = snakeRule.as_string()
    assert 'mem_mb=1200' in ruleString
    assert 'runtime=12' in ruleString
    simple_merfish_data.delete_analysis(task)


def test_snakemake_rule_resources_done_rule_ignores_computed_estimate(
        simple_merfish_data):
    task = testtask.SimpleParallelAnalysisTaskWithResourceEstimate(
        simple_merfish_data,
        parameters={'estimated_memory': 1000, 'estimated_time': 10})
    clusterConfig = {'__default__': {'mem': 8000, 'time': '3:00:00'}}
    snakeRule = snakewriter.SnakemakeRule(task, clusterConfig=clusterConfig)
    ruleString = snakeRule.as_string()
    ruleBlock, doneBlock = ruleString.split(
        'rule %sDone:' % task.get_analysis_name())
    # the task's own rule uses the computed estimate (margined)
    assert 'mem_mb=1200, runtime=12' in ruleBlock
    # the Done rule keeps the plain __default__-derived resources
    assert 'mem_mb=8000, runtime=180' in doneBlock
    simple_merfish_data.delete_analysis(task)


def test_snakemake_generator_embeds_cluster_resources(simple_merfish_data):
    taskDict = {'analysis_tasks': [
        {'task': 'SimpleAnalysisTask',
         'module': 'merlin.analysis.testtask',
         'parameters': {}}
    ]}
    clusterConfig = {'__default__': {'mem': 8000, 'time': '1:00:00'}}

    generator = snakewriter.SnakefileGenerator(
        taskDict, simple_merfish_data, clusterConfig=clusterConfig)
    workflow = generator.generate_workflow()
    outputTask = simple_merfish_data.load_analysis_task('SimpleAnalysisTask')
    assert not outputTask.is_complete()
    with open(workflow) as f:
        workflowContent = f.read()
    assert 'resources: mem_mb=8000, runtime=60' in workflowContent

    # the embedded resources: block doesn't stop local execution
    _run_snakefile_locally(workflow)
    assert outputTask.is_complete()

    shutil.rmtree('.snakemake')
