import numpy as np
import skimage
import cv2
from typing import Tuple
import time

from merlin.core import analysistask
from merlin.analysis.createffc import CreateFfc


ExtentTuple = Tuple[float, float, float, float]


class GenerateMosaic(analysistask.AnalysisTask):

    """
    An analysis task that generates mosaic images by compiling different
    field of views.

    This merges what used to be two separate tasks (GenerateMosaic and
    GenerateMosaicSimple -- the latter is now a thin, deprecated alias of
    this class, see below) into one. Each fov is placed by resampling its
    own (small) tile to the mosaic resolution and slicing it directly into
    the mosaic array -- GenerateMosaicSimple's faster approach, versus the
    old GenerateMosaic's per-fov cv2.warpAffine into the full mosaic-sized
    canvas -- while fov positions still come from the configured
    global_align_task's fov_to_global_transform, so a corrected, non-regular
    fov grid (e.g. from LeastSquaresGlobalAlignment) is placed correctly.

    This fast placement only handles translation/scale transforms (see
    _is_axis_aligned); it does not support a global_align_task whose
    fov_to_global_transform includes rotation or shear (none of the
    currently implemented ones do -- CorrelationGlobalAlignment, the one
    sketched with rotation in mind, is unimplemented).
    """

    def __init__(self, dataSet, parameters=None, analysisName=None):
        super().__init__(dataSet, parameters, analysisName)

        if 'downsample' in self.parameters and 'microns_per_pixel' in self.parameters:
            raise ValueError(
                "GenerateMosaic parameters cannot specify both "
                "'microns_per_pixel' and 'downsample' -- they are two ways "
                "of setting the same mosaic resolution.")

        if 'downsample' in self.parameters:
            downsample = self.parameters['downsample']
            if not isinstance(downsample, int):
                raise ValueError('The downsample parameter must be an integer.')
            if downsample != 1 and downsample % 2 != 0:
                raise ValueError(
                    'The downsample parameter must be 1 or an even integer.')
            self.mosaicMicronsPerPixel = \
                self.dataSet.get_microns_per_pixel() * downsample
        else:
            if 'microns_per_pixel' not in self.parameters:
                self.parameters['microns_per_pixel'] = 3
            if self.parameters['microns_per_pixel'] == 'full_resolution':
                self.mosaicMicronsPerPixel = self.dataSet.get_microns_per_pixel()
            else:
                self.mosaicMicronsPerPixel = self.parameters['microns_per_pixel']

        if 'fov_crop_width' not in self.parameters:
            self.parameters['fov_crop_width'] = 0
        if 'draw_fov_labels' not in self.parameters:
            self.parameters['draw_fov_labels'] = False

        if 'output_format' not in self.parameters:
            self.parameters['output_format'] = 'imagej'
        if self.parameters['output_format'] not in ('imagej', 'ome'):
            raise ValueError("output_format must be 'imagej' or 'ome'.")

        if self.parameters['output_format'] == 'ome':
            # OME output is always written one channel/z per file (pyramid
            # subresolutions are per-image), so it implies separate_files.
            if self.parameters.get('separate_files') is False:
                raise ValueError(
                    "separate_files=False is not supported with "
                    "output_format='ome'.")
            self.parameters['separate_files'] = True
        elif 'separate_files' not in self.parameters:
            self.parameters['separate_files'] = False

        if 'write_pyramidal_tiff' not in self.parameters:
            self.parameters['write_pyramidal_tiff'] = False
        if 'pyramidal_levels' not in self.parameters:
            self.parameters['pyramidal_levels'] = 4
        if self.parameters['write_pyramidal_tiff'] \
                and self.parameters['output_format'] != 'ome':
            raise ValueError("write_pyramidal_tiff requires output_format='ome'.")

    def get_estimated_memory(self):
        return 10000

    def get_estimated_time(self):
        return 30

    def get_dependencies(self):
        return [self.parameters['global_align_task'],
                self.parameters['warp_task']]

    def get_mosaic(self) -> np.ndarray:
        """Get the mosaic generated by this analysis task.

        Returns:
            a 5-dimensional array containing the mosaic. The images are arranged
            as [channel, zIndex, 1, x, y]. The order of the channels is as
            specified in the provided parameters file or in the data
            organization if no data channels are specified.
        """
        return self.dataSet.get_analysis_image_set(self, 'mosaic')

    def _micron_to_mosaic_pixel(self, micronCoordinates,
                                micronExtents) -> np.ndarray:
        """Calculates the mosaic coordinates in pixels from the specified
        global coordinates.
        """
        return np.matmul(self._micron_to_mosaic_transform(micronExtents),
                         np.append(micronCoordinates, 1)).astype(np.int32)[:2]

    def _micron_to_mosaic_transform(self, micronExtents: ExtentTuple) \
            -> np.ndarray:
        s = 1/self.mosaicMicronsPerPixel
        return np.float32(
                [[s*1, 0, -s*micronExtents[0]],
                 [0, s*1, -s*micronExtents[1]],
                 [0, 0, 1]])

    @staticmethod
    def _is_axis_aligned(transform: np.ndarray, tolerance: float = 1e-6) -> bool:
        """True if transform's linear part is pure scaling (no rotation or
        shear), so a fov can be placed by resampling and translating its
        tile directly instead of warping it into the full mosaic canvas.
        """
        offDiagonal = max(abs(transform[0, 1]), abs(transform[1, 0]))
        diagonal = max(abs(transform[0, 0]), abs(transform[1, 1]))
        return offDiagonal <= tolerance * diagonal

    @staticmethod
    def _accumulate(mosaicSum: np.ndarray, mosaicCount: np.ndarray,
                    tile: np.ndarray, x0: int, y0: int) -> None:
        ySlice = slice(y0, y0 + tile.shape[0])
        xSlice = slice(x0, x0 + tile.shape[1])
        mosaicSum[ySlice, xSlice] += tile
        mosaicCount[ySlice, xSlice][tile > 0] += 1

    def _resolve_data_channels(self, dataOrganization):
        if 'data_channels' not in self.parameters:
            return dataOrganization.get_data_channels()
        channels = self.parameters['data_channels']
        if isinstance(channels, str):
            return [dataOrganization.get_data_channel_index(channels)]
        if isinstance(channels, int):
            return [channels]
        return [dataOrganization.get_data_channel_index(x)
                if isinstance(x, str) else x for x in channels]

    def _resolve_z_indexes(self):
        if 'z_index' not in self.parameters:
            return False, range(len(self.dataSet.get_z_positions()))
        zIndex = self.parameters['z_index']
        if zIndex == 'maximum_projection':
            return True, [0]
        if isinstance(zIndex, list):
            return False, zIndex
        if isinstance(zIndex, int):
            return False, [zIndex]

    def _get_chromatic_corrector(self):
        if 'optimize_task' in self.parameters:
            return self.dataSet.load_analysis_task(
                self.parameters['optimize_task']).get_chromatic_corrector()
        return None

    def _get_ffc_field(self, dataChannel: int):
        if 'ffc_task' in self.parameters:
            return self.dataSet.load_analysis_task(
                self.parameters['ffc_task']).get_ffc_field_for_channel(
                dataChannel)
        return None

    def _postprocess_tile(self, rawImage: np.ndarray, fov: int) -> np.ndarray:
        cropWidth = self.parameters['fov_crop_width']
        if cropWidth > 0:
            rawImage[:cropWidth, :] = 0
            rawImage[-cropWidth:, :] = 0
            rawImage[:, :cropWidth] = 0
            rawImage[:, -cropWidth:] = 0

        if self.parameters['draw_fov_labels']:
            rawImage = cv2.putText(
                rawImage, str(fov),
                (int(0.2*rawImage.shape[0]), int(0.2*rawImage.shape[1])),
                0, 10, (65000, 65000, 65000), 20)

        downsampleScale = \
            self.dataSet.get_microns_per_pixel() / self.mosaicMicronsPerPixel
        if downsampleScale != 1:
            rawImage = skimage.transform.rescale(
                rawImage, downsampleScale, anti_aliasing=True,
                preserve_range=True)

        return rawImage

    def load_tile(self, fov: int, zIndex: int, dataChannel: int) -> np.ndarray:
        """Load, crop, label, and resample a single fov/z/channel tile to
        the mosaic resolution, without placing it. Used directly for a
        single z index, and (with the z gate skipped) as the last step for
        a maximum-projected tile in _build_mosaic.
        """
        chromaticCorrector = self._get_chromatic_corrector()

        if zIndex < len(self.dataSet.get_z_positions(fov)):
            rawImage = self.warpTask.get_aligned_image(
                fov, dataChannel, zIndex, chromaticCorrector)
            ffcField = self._get_ffc_field(dataChannel)
            if ffcField is not None:
                rawImage = CreateFfc.apply_ffc(
                    rawImage, ffcField).astype(rawImage.dtype)
        else:
            # this fov has no data at this depth (ragged z-stack) -- a blank
            # tile keeps the placement/averaging below unchanged, since an
            # all-zero contribution is already treated as "not imaged here"
            rawImage = np.zeros(
                self.dataSet.get_image_dimensions(), dtype=np.uint16)

        return self._postprocess_tile(rawImage, fov)

    def _build_mosaic(self, alignTask, micronToMosaicTransform: np.ndarray,
                      mosaicShape: Tuple[int, int], dataChannel: int,
                      zIndex: int, maximumProjection: bool) -> np.ndarray:
        mosaicSum = np.zeros(mosaicShape, dtype=np.float32)
        mosaicCount = np.zeros(mosaicShape, dtype=np.uint8)

        fovs = self.dataSet.get_fovs()
        sampleTransform = np.matmul(
            micronToMosaicTransform, alignTask.fov_to_global_transform(fovs[0]))
        if not self._is_axis_aligned(sampleTransform):
            raise NotImplementedError(
                "GenerateMosaic's tile-based placement only supports "
                "translation/scale global alignments (e.g. "
                "SimpleGlobalAlignment, LeastSquaresGlobalAlignment); '%s' "
                "returns a rotated or sheared fov_to_global_transform, which "
                "merging GenerateMosaicSimple's faster placement into "
                "GenerateMosaic dropped support for."
                % self.parameters['global_align_task'])

        for fov in fovs:
            if maximumProjection:
                fovZCount = len(self.dataSet.get_z_positions(fov))
                chromaticCorrector = self._get_chromatic_corrector()
                rawImage = np.max(
                    [self.warpTask.get_aligned_image(
                        fov, dataChannel, z, chromaticCorrector)
                     for z in range(fovZCount)], axis=0)
                ffcField = self._get_ffc_field(dataChannel)
                if ffcField is not None:
                    rawImage = CreateFfc.apply_ffc(
                        rawImage, ffcField).astype(rawImage.dtype)
                tile = self._postprocess_tile(rawImage, fov)
            else:
                tile = self.load_tile(fov, zIndex, dataChannel)

            transform = np.matmul(
                micronToMosaicTransform, alignTask.fov_to_global_transform(fov))
            originX, originY = transform[0, 2], transform[1, 2]
            baseX, baseY = int(np.floor(originX)), int(np.floor(originY))
            nudgeX, nudgeY = originX - baseX, originY - baseY
            if nudgeX != 0 or nudgeY != 0:
                # sub-pixel correction so a fractional fov position doesn't
                # get rounded away
                tform = skimage.transform.AffineTransform(
                    translation=(nudgeX, nudgeY))
                tile = skimage.transform.warp(
                    tile, tform.inverse, order=1, mode='constant', cval=0,
                    preserve_range=True)

            self._accumulate(mosaicSum, mosaicCount, tile, baseX, baseY)

        # average overlapping fovs; a pixel imaged by only one fov is
        # unaffected since mosaicCount is 1 there
        divisionMask = mosaicCount > 0
        mosaicSum[divisionMask] = mosaicSum[divisionMask] / mosaicCount[divisionMask]
        return mosaicSum.astype(np.uint16)

    def _write_imagej_mosaics(self, alignTask, micronToMosaicTransform,
                              mosaicShape, dataOrganization, dataChannels,
                              zIndexes, maximumProjection):
        if self.parameters['separate_files']:
            imageDescription = self.dataSet.analysis_tiff_description(1, 1)
            for d in dataChannels:
                for z in zIndexes:
                    with self.dataSet.writer_for_analysis_images(
                        self,
                        'mosaic_%s_%i' % (dataOrganization.get_data_channel_name(d), z),
                        imagej = True) as outputTif:
                            mosaic = self._build_mosaic(
                                alignTask, micronToMosaicTransform, mosaicShape,
                                d, z, maximumProjection)
                            outputTif.write(mosaic, photometric='MINISBLACK', contiguous=True,
                                        metadata=imageDescription)

        else:
            imageDescription = self.dataSet.analysis_tiff_description(
                len(zIndexes), len(dataChannels))
            with self.dataSet.writer_for_analysis_images(
                    self, 'mosaic', imagej = True) as outputTif:
                for d in dataChannels:
                    for z in zIndexes:
                        print(f'starting data channel {d}, z index {z}.')
                        mosaic = self._build_mosaic(
                            alignTask, micronToMosaicTransform, mosaicShape,
                            d, z, maximumProjection)
                        outputTif.write(mosaic, photometric='MINISBLACK', contiguous=True,
                                       metadata=imageDescription)

    def _write_ome_mosaics(self, alignTask, micronToMosaicTransform,
                          mosaicShape, dataOrganization, dataChannels,
                          zIndexes, maximumProjection):
        for d in dataChannels:
            dataChannelName = dataOrganization.get_data_channel_name(d)
            for z in zIndexes:

                print(f'starting data channel {d}, z index {z}.', flush=True)
                mosaic_name = f'mosaic_{dataChannelName}_{z}'
                with self.dataSet.writer_for_analysis_images(self, mosaic_name,
                    imagej=False, ome=True) as outputTif:

                        t0 = time.time()
                        mosaic = self._build_mosaic(
                            alignTask, micronToMosaicTransform, mosaicShape,
                            d, z, maximumProjection)
                        t1 = time.time()
                        print(f'channel {d}, z index {z} mosaic prepared in {t1 - t0:.2f} seconds.', flush=True)

                        metadata = {'axes': 'YX'}
                        options = dict(
                            photometric='MINISBLACK',
                            tile=(256, 256),
                            compression='lzw',
                            contiguous=True
                        )

                        if self.parameters['write_pyramidal_tiff']:
                            subresolutions = int(self.parameters['pyramidal_levels'])

                            outputTif.write(mosaic[:, :],
                                        subifds=subresolutions,
                                        metadata=metadata,
                                        **options)

                            for level in range(subresolutions):
                                print(f'writing channel {d}, z index {z} mosaic level {level}', flush=True)
                                mag = 2 ** (level + 1)
                                outputTif.write(
                                    mosaic[::mag, ::mag],
                                    subfiletype=1,
                                    **options,
                                )

                        else:
                            outputTif.write(mosaic[:, :],
                                metadata=metadata,
                                **options)

                        t2 = time.time()
                        print(f'channel {d}, z index {z} mosaic written in {t2 - t1:.2f} seconds.', flush=True)

    def _run_analysis(self):

        alignTask = self.dataSet.load_analysis_task(
                self.parameters['global_align_task'])
        self.warpTask = self.dataSet.load_analysis_task(
                self.parameters['warp_task'])

        micronExtents = alignTask.get_global_extent()
        micronToMosaicTransform = self._micron_to_mosaic_transform(micronExtents)
        self.dataSet.save_numpy_txt_analysis_result(
            micronToMosaicTransform, 'micron_to_mosaic_pixel_transform', self)
        mosaicDimensions = tuple(self._micron_to_mosaic_pixel(
                micronExtents[-2:], micronExtents))
        mosaicShape = tuple(np.flip(mosaicDimensions, axis=0))

        dataOrganization = self.dataSet.get_data_organization()
        dataChannels = self._resolve_data_channels(dataOrganization)
        maximumProjection, zIndexes = self._resolve_z_indexes()

        print('generating mosaic for \nchannels: {}\nz indexes: {}'.format(dataChannels, zIndexes))

        if self.parameters['output_format'] == 'ome':
            self._write_ome_mosaics(
                alignTask, micronToMosaicTransform, mosaicShape,
                dataOrganization, dataChannels, zIndexes, maximumProjection)
        else:
            self._write_imagej_mosaics(
                alignTask, micronToMosaicTransform, mosaicShape,
                dataOrganization, dataChannels, zIndexes, maximumProjection)


class GenerateMosaicSimple(GenerateMosaic):

    """
    Deprecated alias for GenerateMosaic, kept so existing analysis-parameters
    files that reference "GenerateMosaicSimple" keep working. The fast,
    tile-based placement it introduced is now GenerateMosaic's only
    placement method (see that class's docstring); this subclass only
    restores GenerateMosaicSimple's original defaults -- a wider fov crop,
    and OME (rather than ImageJ) tiff output -- for configs that relied on
    them implicitly rather than setting them.
    """

    def __init__(self, dataSet, parameters=None, analysisName=None):
        parameters = dict(parameters) if parameters else {}
        parameters.setdefault('downsample', 1)
        parameters.setdefault('fov_crop_width', 100)
        parameters.setdefault('output_format', 'ome')
        super().__init__(dataSet, parameters, analysisName)
